### ISSUE TITLE
Group reports improvements on visualisations

### ISSUE THREAD

**Issue by jokedurnez** [nipreps/mriqc#467] opened 2017-04-25 01:11 UTC
It would be really cool if you roll over one subject in the group report, that this subjects' datapoint would also be highlighted in all other plots.  Could be useful to see if this subject is an outlier only on one metric, or has extreme values on multiple/all scores.
Also: a search for a subject in the group reports would be cool.  Usecase: I'm adding new subjects every 2-3 weeks.  I'll look at each individual report, but the group reports are going to be more difficult to look at.  If I can look up the new subject and see all of its datapoints, obvious outliers on all metrics will become easier to spot.

**Comment by chrisfilo** [comment] 2017-04-25 01:22
Or - more general: a search option for highlighting one subject.

Partially a duplicate of #447

**Comment by yjmantilla** [comment] 2020-11-20 03:31
Is there any progress regarding this issue? Would be awesome if it was implemented.

Anyway thank you for all the work, the tool is amazing.

**Comment by oesteban** [comment] 2020-11-23 08:48
Hi @yjmantilla, unfortunately, there isn't any advance. The maintainers do not have enough time to make any progress and we are barely meeting the minimal updates necessary to keep the project sane. If you know anything about D3.js or you can bring some expertise to the project, new contributors are most definitely welcome.

**Comment by oesteban** [comment] 2022-03-14 09:06
(follow up in newly opened issue)

**Closed by oesteban** 2022-03-14 09:06 UTC
Labels: feature, reports
