### ISSUE TITLE
Spatial normalization and skull stripping failure on T1w images

### ISSUE THREAD

**Issue by parekhpravesh** [nipreps/mriqc#855] opened 2020-08-11 16:48 UTC
Hello,

There are quite a few subjects for which skull stripping/spatial normalization seems to fail: on visual inspection in the report, I can see quite a bit of non-brain tissues and in a few cases, the brain tissue is lost. Here is one such example
![sub-SZ146-report](https://user-images.githubusercontent.com/8792123/89924039-14d7b800-dc1f-11ea-85d4-e6aaf9272770.png)

The current example is 192 slices, 256x256 T1-weighted image which doesn't really have any visible MR-artefacts or brain pathology. This is data from Philips Ingenia CX but I am also seeing this problem with Siemens Skyra. 

Version information: MRIQC: 15.0 (run via Docker) [problem also exists in 15.2]

Questions:
1) What could be causing this and is there a way to handle this at the moment?
2) Which QC metrics would be directly impacted with this problem?

Related posts: #768 (squiggly lines in many subjects and weird brain masks), #788 might fix these? Possibly related to #554

**Comment by oesteban** [comment] 2022-03-14 08:50
This is a duplicate of #554 and will be followed within #933.

**Closed by oesteban** 2022-03-14 08:50 UTC
